esphome:
  name: boiler_room
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: "Zebenkstis"
  password: !secret wifi_zebenkstis_password
  ap:
    ssid: "Boiler Room Fallback Hotspot"
    password: !secret ap_fallback_password
captive_portal:
time:
  - platform: homeassistant
    id: homeassistant_time
sensor:
  - platform: uptime
    id: uptime_sec
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s  
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Pellets tank level %"
    update_interval: 60s
    filters:
    - lambda: return (0.68-x)*(100/0.68);
    unit_of_measurement: "%"
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Pellets tank level cm"
    update_interval: 60s
    filters:
    - lambda: return (0.68-x)*100;
    unit_of_measurement: "cm"  
  - platform: dht
    pin: D5
    temperature:
      name: "Boiler room temperature"
    humidity:
      name: "Boiler room humidity %"
    update_interval: 60s  
text_sensor:
  - platform: template
    name: Uptime
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    icon: mdi:clock-start
    update_interval: 60s
logger:
api:
  password: !secret api_password
ota:
  safe_mode: True
  password: !secret ota_password
