esphome:
  name: zeimenos_139a1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "donatas"
  password: !secret wifi_password

  ap:
    ssid: "Fallback Hotspot"
    password: !secret ap_password

dallas:
  - pin: D1
    update_interval: 5s

sensor:
  - platform: dht
    pin: D5
    model: DHT11
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s
  - platform: dallas
    name: dallas1
    address: 0x1300000575E44828

  - platform: adc
    pin: A0
    name: "MQ-6"
    update_interval: 5s
    filters:
      - multiply: 100
    unit_of_measurement: "%"
    icon: "mdi:percent"

captive_portal:
logger:
api:
ota:
